AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for static website hosting with S3 Bucket.

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # BucketName: 'cca-cw1-bucket-1' # It's recommended to remove the BucketName to avoid global namespace issues
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
        ErrorDocument: 'error.html'
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt [S3Bucket, DomainName]
            Id: S3Origin
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: 'index.html'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: 'redirect-to-https'
          AllowedMethods:
            - 'GET'
            - 'HEAD'
            - 'OPTIONS'
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: 'none'
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CacheBehaviors:
          - PathPattern: 'img/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'
          - PathPattern: 'css/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'
          - PathPattern: 'js/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'
          - PathPattern: 'fonts/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'

Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref S3Bucket

  S3BucketWebsiteURL:
    Description: "URL of the S3 Bucket Hosting the Website"
    Value: !GetAtt [S3Bucket, WebsiteURL]

  DistributionId:
    Description: "ID of the CloudFront distribution"
    Value: !Ref CloudFrontDistribution

  DistributionDomainName:
    Description: "Domain name of the CloudFront distribution"
    Value: !GetAtt [CloudFrontDistribution, DomainName]
