AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cca-cw1-bucket-1'
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt [S3Bucket, DomainName]
            Id: S3Origin
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: 'index.html'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: 'redirect-to-https'
          AllowedMethods:
            - 'GET'
            - 'HEAD'
            - 'OPTIONS'
  CloudFrontPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'CloudFrontCreateDistributionPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'cloudfront:CreateDistribution'
            Resource: '*'
      Users:
        - 'S3_USER'
Outputs:
  BucketName:
    Value: !Ref S3Bucket
  DistributionId:
    Value: !Ref CloudFrontDistribution
