AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cca-cw1-bucket-1'
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt [S3Bucket, DomainName]
            Id: S3Origin
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: 'index.html'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: 'redirect-to-https'
          AllowedMethods:
            - 'GET'
            - 'HEAD'
            - 'OPTIONS'
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CacheBehaviors:
          - PathPattern: 'img/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
          - PathPattern: 'css/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
          - PathPattern: 'js/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
          - PathPattern: 'fonts/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000

Outputs:
  BucketName:
    Value: !Ref S3Bucket
  DistributionId:
    Value: !Ref CloudFrontDistribution
