
name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://cca-cw1-bucket --delete --exclude '.*/*' --exclude '.*'

      - name: Check if Stack Exists
        id: check_stack
        run: |
          if aws cloudformation describe-stacks --stack-name stack &> /dev/null; then
            echo "StackExists=true"
          else
            echo "StackExists=false"
          fi
        continue-on-error: true

      - name: Create or Update Stack
        run: |
          if [ "${{ steps.check_stack.outputs.StackExists }}" == "true" ]; then
            aws cloudformation update-stack --stack-name stack --template-body file://.github/workflows/cloudformation-template.yaml --capabilities CAPABILITY_IAM
          else
            aws cloudformation create-stack --stack-name stack --template-body file://.github/workflows/cloudformation-template.yaml --capabilities CAPABILITY_IAM
          fi