name: Deploy CloudFormation Stack and website to S3 bucket

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check stack state
        id: check_state
        run: |
          STATE=$(aws cloudformation describe-stacks --stack-name stack --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "")
          echo "STACK_STATE=$STATE" >> $GITHUB_ENV

      - name: Delete stack if in ROLLBACK_COMPLETE state
        if: env.STACK_STATE == 'ROLLBACK_COMPLETE'
        run: |
          aws cloudformation delete-stack --stack-name stack
          aws cloudformation wait stack-delete-complete --stack-name stack

      - name: Check if stack exists
        id: check_exists
        run: |
          EXISTS=$(aws cloudformation describe-stacks --stack-name stack --query "Stacks[0].StackName" --output text 2>/dev/null || echo "")
          if [ "$EXISTS" == "stack" ]; then
            echo "STACK_EXISTS=true" >> $GITHUB_ENV
          else
            echo "STACK_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create stack if not exists
        if: env.STACK_EXISTS == 'false'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: stack
          template: stack/cloudformation-template.yaml
          no-fail-on-empty-changeset: "1"
          capabilities: "CAPABILITY_NAMED_IAM"

      - name: Print CloudFormation Outputs
        run: |
          aws cloudformation describe-stacks --stack-name stack --query "Stacks[0].Outputs"

#      - name: Deploy to S3 bucket
#        run: |
#          aws s3 sync src/ s3://$(aws cloudformation describe-stacks --stack-name stack --query "Stacks[0].Outputs[?OutputKey=='S3Bucket'].OutputValue" --output text) --delete


