
name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://cca-cw1-bucket --delete --exclude '.*/*' --exclude '.*'

      - name: Create Change Set
        run: |
          aws cloudformation create-change-set --stack-name stack --template-body .github/workflows/cloudformation-template.yaml --change-set-name my-changeset --capabilities CAPABILITY_IAM

      - name: Execute Change Set
        run: |
          aws cloudformation execute-change-set --stack-name stack --change-set-name my-changeset